### PR TITLE
Unpin `esmf` and set it to free like upstream and bump build number

### LINKED ISSUE #154: Unpin `esmf` to free from `esmf <8.6.0`
Hey folks, I checked [upstream](https://github.com/NCAR/ncl/blob/develop/.build/envs/Linux.yml) and I see `esmf` is free there, am gonna open a PR unppinning it here too, if that's OK with you - we're hitting env solving issues due to the pin :beer:

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~[ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #154

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
Hi @valeriupredoi :wave:. Inspecting upstream, you may have seen that that file was last touched 2 years ago, whereas, as I am sure you saw in the git-blame, the pin here was added just a month or so ago. For more explanation, have a look at the PR that introduced the pin, specifically https://github.com/conda-forge/ncl-feedstock/pull/148#issuecomment-2092434499.

**Comment by zklaus** [comment]
If you do come up with a patch that fixes NCL, I personally would be happy to accept.

**Comment by valeriupredoi** [comment]
ma man @zklaus - good to see you here :beer: Indeed, when the first test failed I realized it's not as breezy as I initially thought it'd be, and there's a good reason why the pin is on here (never bothered checking the gitblame, though, I admit to that). Unfortunately patching NCL is well beyond my area of expertise, do you have a wee bit time to tell me what I should do and then maybe I can get someone like @schlunma who speaks NCL to help out? Cheers, bud :beer:

**Comment by valeriupredoi** [comment]
PS this can prob be closed now, since we'll remove the pin off a new build that will have included the patch upstream

**Comment by akrherz** [comment]
Closing per suggestion

**Comment by zklaus** [comment]
@valeriupredoi, to be clear: upstream hasn't seen any development in over 2 years, despite a number of more or less ready open PRs that fix immediate problems, so I wouldn't hold my breath for an upstream release.
It feels like this is the end for NCL.

However, to tackle these problems, if you are still interested, you don't need knowledge of NCL; only Fortran, since that is the language in which NCL is written.

**Pull request closed without merging**
