### PR TITLE
No gcc

### PR DESCRIPTION
**Pull request by ocefpaf**
@khallock this should help with some of the channel mixing issues we are experiencing lately.

xref.: https://github.com/conda-forge/pynio-feedstock/pull/50

### CODE REVIEW

**Comment by khallock** [comment]
I wish there was a way to have conda smithy keep "local changes" like that so we wouldn't have to worry about this with every rerender.

**Comment by ocefpaf** [comment]
> I wish there was a way to have conda smithy keep "local changes" like that so we wouldn't have to worry about this with every rerender.

And there are two change like that here now :-(

But the real solution would be to find a way for the cairo/X11 issue. I'm going to push that forward a little harder so we can drop the workarounds.

**Comment by khallock** [comment]
Is the second change the removal of the defaults channel? If so, should we be doing that for PyNIO and PyNGL as well?

**Comment by ocefpaf** [comment]
> Is the second change the removal of the defaults channel? If so, should we be doing that for PyNIO and PyNGL as well?

Yep. That is temporary until https://github.com/conda/conda/issues/7626 is solved.
I think I got both PyNIO (merged) and PyNGL (unmerged) already.

**Comment by khallock** [comment]
`dyld: Library not loaded: @rpath/libgomp.1.dylib`

What's the best way to get `libgomp.1.dylib` if we don't require libgcc as a run dep or allow the usage of the defaults channel? The defaults channel libgfortran includes this lib, but conda-forge libgfortran does not.

**Comment by ocefpaf** [comment]
> What's the best way to get libgomp.1.dylib if we don't require libgcc as a run dep or allow the usage of the defaults channel?

I don't think there is one but let me ping @isuruf here just to be sure.

I guess we should vendorize `gcc` on `conda-forge` too for the rare cases where it is needed, but let's wait on @isuruf answer before I do that, he may know some clang-fu that may help is with this.

**Comment by isuruf** [comment]
We should fix https://github.com/conda-forge/libgfortran-feedstock/issues/13

**Comment by ocefpaf** [comment]
> We should fix conda-forge/libgfortran-feedstock#13

Thanks! Just sent https://github.com/conda-forge/libgfortran-feedstock/pull/14

**Pull request merged**
