### PR TITLE
Fix osx-arm64 build

### LINKED ISSUE #134: NCL executable missing
I installed the ncl package on a new MacBook Pro (Apple M1 Pro). The message says the conda-forge/osx-arm64::ncl-6.6.2-h5d9bed2_44 package will be installed, but the actual ncl executable is not in the bin directory or anywhere else from what I can tell. Can someone confirm?

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #134.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
Alright, the sanity check correctly detects the insanity. Now on to fixing it.

**Comment by akrherz** [comment]
```
2023-05-11T15:16:07.4219690Z flex ncl.l
2023-05-11T15:16:07.4232520Z make[4]: flex: Bad CPU type in executable
```
This looks just like my gdal osx issues with `flex` needing to be in build and not host sections?!?!

**Comment by zklaus** [comment]
I think all of the following (found via `ag "bad cpu"`) indicates a problem with custom build tools that must be compiled before the build proper
```
8121:2023-05-11T15:15:53.8957750Z make[4]: ../../.././ni/src/nyacc/nyacc: Bad CPU type in executable
23256:2023-05-11T15:16:07.4232500Z make[4]: flex: Bad CPU type in executable
23262:2023-05-11T15:16:09.8392280Z make[4]: flex: Bad CPU type in executable
39571:2023-05-11T15:21:24.6315160Z make[4]: ../../.././common/src/fontcap/fontc: Bad CPU type in executable
39801:2023-05-11T15:21:27.8359700Z make[4]: ../../.././common/src/graphcap/graphc: Bad CPU type in executable
39892:2023-05-11T15:21:36.3266940Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
40577:2023-05-11T15:21:50.9775140Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
40584:2023-05-11T15:21:52.0019360Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
41886:2023-05-11T15:22:25.9888890Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
43545:2023-05-11T15:23:15.3131990Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
44017:2023-05-11T15:23:26.5715260Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
45542:2023-05-11T15:24:17.1117320Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
55219:2023-05-11T15:28:27.9695700Z make[5]: ./ConvertMapData: Bad CPU type in executable
55232:2023-05-11T15:28:29.9475560Z make[5]: ./WritePlotcharData: Bad CPU type in executable
55247:2023-05-11T15:28:32.1443540Z make[5]: ./pwritxnt: Bad CPU type in executable
74909:2023-05-11T15:34:45.0949070Z /bin/sh: ./rgb: Bad CPU type in executable
75344:2023-05-11T15:36:23.8363700Z make[4]: ../../.././common/src/fontcap/fontc: Bad CPU type in executable
75351:2023-05-11T15:36:23.8383090Z make[4]: ../../.././common/src/graphcap/graphc: Bad CPU type in executable
75381:2023-05-11T15:36:25.3040480Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
75402:2023-05-11T15:36:30.8389500Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
75407:2023-05-11T15:36:31.8755670Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
75436:2023-05-11T15:36:39.4118660Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
75484:2023-05-11T15:36:51.9869660Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
75510:2023-05-11T15:36:58.7056110Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
75543:2023-05-11T15:37:06.9458870Z /bin/sh: ../../../.././ncarg2d/src/libncarg/Iftran/Iftran: Bad CPU type in executable
76173:2023-05-11T15:37:49.2578660Z make[5]: ./ConvertMapData: Bad CPU type in executable
76181:2023-05-11T15:37:49.4023020Z make[5]: ./WritePlotcharData: Bad CPU type in executable
76189:2023-05-11T15:37:49.5413460Z make[5]: ./pwritxnt: Bad CPU type in executable
78556:2023-05-11T15:38:36.7260860Z /bin/sh: ./rgb: Bad CPU type in executable
```

**Comment by zklaus** [comment]
There is an additional wrinkle that also affects osx-64, which is that with clang 15,
> The -Wint-conversion warning diagnostic for implicit int <-> pointer conversions now defaults to an error in all C language modes. It may be downgraded to a warning with -Wno-error=int-conversion, or disabled entirely with -Wno-int-conversion.

(from https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics)

I added a patch to change the two locations where this seems to happen, but probably downgrading to a warning is more reasonable.

**Pull request closed without merging**
