### PR TITLE
Pin gdal

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by khallock** [comment]
@ocefpaf, I think we still need to include `brew cask install xquartz` in .travis.yml. Do you know what the status of the conda-forge Xorg packages is? Is there any chance we can adopt those soon?

**Comment by ocefpaf** [comment]
> @ocefpaf, I think we still need to include `brew cask install xquartz` in .travis.yml.

My bad I re-rendered and did not pay attention to that!

> Do you know what the status of the conda-forge Xorg packages is? Is there any chance we can adopt those soon?

To be honest I don't. @pkgw is probably knows better.

**Comment by pkgw** [comment]
@ocefpaf @khallock Well, the packages are available and functional, but the discussion about how closely/deeply we want to integrate them has more or less stalled. It seems that more and more packages are starting to use them, though. If this package isn't too deep in the dependency stack I might suggest just going ahead and adding X.org dependencies if they would make life easier ...

**Comment by ocefpaf** [comment]
I vote to try the `xorg` packages. It will improve shipping `ncl` and it won't interfere with `conda-forge`'s dependency stack.

**Pull request merged**
