### PR TITLE
Rebuild for proj4 5.2.0

### PR DESCRIPTION
**Pull request by xylar**
This is needed for compatibility with basemap.

Add xylar as a maintainer.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@ocefpaf, could we maybe make a branch (e.g. `proj4_5.2.0`) on `conda-forge/ncl-feedstock` for this to be merged to?

**Comment by xylar** [comment]
Currently, it is difficult to install `basemap` and `ncl` in the same conda environment because `basemap` uses an older version of `proj4`.  Ideally, `basemap` would be released with support for the latest `proj4` but that doesn't seem likely to happen anytime soon.  So I'm hoping to make a compatible `ncl` build instead.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@ocefpaf, do you have advice on the preferred way to turn off the `osx_fortran_compiler_version7` build, the dependencies don't seem to exist?

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> @ocefpaf, do you have advice on the preferred way to turn off the `osx_fortran_compiler_version7` build, the dependencies don't seem to exist?

If you don't care about it just merge with that item failing. No need to skip it. This is for the branch, right?

**Comment by xylar** [comment]
> If you don't care about it just merge with that item failing. No need to skip it. This is for the branch, right?

@ocefpaf, that's right.  Could you make a branch here for proj4 5.2.0?  Then, I can change the base to point to that branch.  I'm not yet a maintainer, so I'll have to rely on you to merge this PR.

**Comment by ocefpaf** [comment]
> @ocefpaf, that's right. Could you make a branch here for proj4 5.2.0? Then, I can change the base to point to that branch. I'm not yet a maintainer, so I'll have to rely on you to merge this PR.

Let me try something different first. I think I can create a build matrix and avoid the branch. Hold on...

**Comment by xylar** [comment]
> Let me try something different first. I think I can create a build matrix and avoid the branch. Hold on...

Sounds good!  It looks like this branch needs to be rebased as well, since there's been a recent merge.

**Comment by xylar** [comment]
@ocefpaf, Great, even the gfortran7 version built this time!  So once you figure out the matrix build, let me know.  I should be able to rebase and we should be good to merge.

**Comment by xylar** [comment]
Closing in favor of #67. Thanks @ocefpaf!

**Pull request closed without merging**
