### PR TITLE
Add port to Proj6 API as patch

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This grew into quite a large PR. As such it contains several things that IMHO can not be done in separate PRs, mostly due to the fact that the CI environment has evolved quite a bit since the last update of this feedstock.
The good news is that I believe this catches us up completely. The bad news is that it's quite a lot. In detail this contains:

- Migrations for
  - libnetcdf481 (via libnetcdf480)
  - hdf51121
  - proj801
- Patches
  - Adding HDF5 compatibility macro define for hdf51121
  - Porting NCL to Proj6 API

I have also removed Python as a build dependency because I think it is just not needed. This may have been a change at some point in the past, since `Configure` in upstream sources says
> The python stuff is commented out for now. One should use
> the "setup.py" method for building python software, and not
> the ymake system.

but in any case, the build and all the tests work.

I'd be really grateful for a proper review in this case, or comments of how to address this in a different way.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
This PR adds a patch to port NCL to the new Proj API that was introduced in Proj 6 (2018) and is mandatory since the old API was removed in Proj 8 (2021).

I would like to get some feedback on whether this is considered appropriate, or too much of a change for a patch.
What's your opinion, @conda-forge/ncl?

There remain technical issues, but I believe that the build error is due to a bug in the hdfeos5 package, that has been fixed in conda-forge/hdfeos5-feedstock#32 and that will go away once the CI picks up the new build.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@zklaus, is it possible to hold off on hdf5 and/or libnetcdf migration as part of this PR or are they required for all the dependencies to be in place?  I'm guessing the latter.  But if possible it's usually best to have various builds with various dependency combinations.  So I could imagine in this case first merging without either migration, then doing the libnetcdf migration, and finally doing the hdf5 migration.

Given that NCL has been neglected for so long, whatever you need to do to get this in is great.  If that means doing all 3 migrations at once, so be it.

**Comment by xylar** [comment]
Also, please add yourself as a maintainer if you're willing.

**Comment by zklaus** [comment]
@xylar, thanks for your comments. I did start out trying to do only one thing, but dependency hell spiraled out of control. Having said that, I'll make one more try with the benefit of hindsight at #111, let's see if I manage.

Of course I am willing to be a maintainer. I was already added in #95 :smile:

**Comment by xylar** [comment]
> Of course I am willing to be a maintainer. I was already added in #95

Ah, sorry, I somehow looked somewhere and didn't see you in the list.  Clearly I lost track...

**Comment by xylar** [comment]
It looks like #111 isn't succeeding.  I'm fine with you merging this instead.

**Pull request merged**
