### PR TITLE
rebuild with Jasper 2

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Obsoletes #110 
also adds myself as a maintainer, would be happy to help out more.

closes #114

### CODE REVIEW

**Comment by akrherz** [comment]
Bah, if the bot comes back with a good PR and want to take that, no worries.  I'd just like to help out more and be added as a maintainer :)

**Comment by akrherz** [comment]
well shucks
```
2021-09-29T17:20:45.0187067Z enc_jpeg2000.c: In function 'enc_jpeg2000':
2021-09-29T17:20:45.0188181Z enc_jpeg2000.c:124:10: error: 'jas_image_t' {aka 'struct <anonymous>'} has no member named 'inmem_'
2021-09-29T17:20:45.0188783Z   124 |     image.inmem_=1;
2021-09-29T17:20:45.0189164Z       |          ^
2021-09-29T17:20:45.0210731Z make[3]: *** [libgrib2c.a(enc_jpeg2000.o)] Error 1
```

**Comment by akrherz** [comment]
:eyes: conda-forge/g2clib-feedstock#24

**Comment by xylar** [comment]
Just merged that one.  Somehow missed it if I got an notification...

**Comment by xylar** [comment]
I think it would have been better to patch conda-forge's g2clib than to have the patches in a vendored g2clib.  Is that something anyone has time or energy to try out?

**Comment by akrherz** [comment]
Reviewing [g2clib](https://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/) changelog does not look promising that the NCL modifications made it upstream

```
g2libc-1.6.0 - October  2015 - Added PDT 4.57, 4.60, 4.61 and
                             - Allow a forecast time to be negative

g2libc-1.6.2 - December 2020 - Added Doxygen (minor changes)

g2libc-1.6.3 - March    2021 - Assign long g2int and unsigned long g2int
```

May have to patch the vendored lib here, more boggling....

**Comment by xylar** [comment]
But the NCL patches to g2libc could be added to conda-forge's g2libc, right?

**Comment by akrherz** [comment]
@xylar , there may be more trouble here than just that.  I don't think g2clib supports Jasper 2 at all.  I am now looking at what GDAL vendors, it may be better :/

**Comment by akrherz** [comment]
@xylar or somebody, please remove the automerge.  This additional patch may need discussion.  From upstream g2clib
```
#ifdef JAS_1_700_2
    image.clrspc_=JAS_CLRSPC_SGRAY;         /* grayscale Image */
    image.cmprof_=0;
#endif
//    image.inmem_=1;
```

:hand_over_mouth:

**Comment by akrherz** [comment]
So this PR was green before master got updated underneath of me :)  rebasing now

This at least Obsoletes #114

**Comment by xylar** [comment]
I'm going to put back `automerge`.

**Comment by zklaus** [comment]
Just wanted to say thanks for all the work @akrherz and @xylar ! :+1:

**Pull request merged**
