### PR TITLE
Re render

### LINKED ISSUE #42: Rebuild with hdf5 1.10.3
My colleagues and I are running into incompatibilities between the current conda-forge version of NCL and the latest version of NCO, specifically the supported version of hdf5.  Any plans to rebuild with the latest pinnings?

cc @sterlingbaldwin

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #42

### CODE REVIEW

**Comment by ocefpaf** [comment]
Needs https://github.com/conda-forge/gdal-feedstock/pull/232

**Comment by ocefpaf** [comment]
Not sure what is going on macOS here :-/

**Comment by ocefpaf** [comment]
> It looks like our X11/XQuartz workaround is broken... I found this in the build log:
> `No X11 libs found. Exiting...`
> 
> I'll take a look at this shortly, thanks @ocefpaf!

Ah! The re-rendering may have removed that. (I always forget about that part.)

**Comment by khallock** [comment]
> > It looks like our X11/XQuartz workaround is broken... I found this in the build log:
> > `No X11 libs found. Exiting...`
> > I'll take a look at this shortly, thanks @ocefpaf!
> 
> Ah! The re-rendering may have removed that. (I always forget about that part.)

Oh, of course! This recipe has been working so well for the past few months, I forgot the usual re-render routine too.

**Comment by ocefpaf** [comment]
Thanks @khallock for the assist!

**Pull request merged**
