### PR TITLE
Fix upload channel [ci skip] [skip ci]

### PR DESCRIPTION
**Pull request by khallock**

### CODE REVIEW

**Comment by khallock** [comment]
@ocefpaf, PR #31 built properly but because I forgot to re-render the feedstock, the packages were uploaded to the main channel (see: https://anaconda.org/conda-forge/ncl/files). Could you please change the label on the two `ncl-6.5.0.dev0-blas_openblas_0.tar.bz2` packages to `dev` instead of `main`? Relabeling those would have the same effect as allowing this PR to finish, so to save time and CI resources I marked this PR as `ci skip`.

**Comment by ocefpaf** [comment]
> @ocefpaf, PR #31 built properly but because I forgot to re-render the feedstock, the packages were uploaded to the main channel (see: https://anaconda.org/conda-forge/ncl/files). Could you please change the label on the two `ncl-6.5.0.dev0-blas_openblas_0.tar.bz2` packages to `dev` instead of `main`? 

Sure, can you check if I got it right: https://anaconda.org/conda-forge/ncl/files?version=6.5.0.dev0

> Relabeling those would have the same effect as allowing this PR to finish, so to save time and CI resources I marked this PR as `ci skip`.

:+1:

**Comment by khallock** [comment]
> Sure, can you check if I got it right: https://anaconda.org/conda-forge/ncl/files?version=6.5.0.dev0

Looks good to me!

I'm not sure why CircleCI is trying to build this...

**Comment by ocefpaf** [comment]
> I'm not sure why CircleCI is trying to build this...

I guess that CircleCI needs the skip on the GiHub message rather than the commit message.

**Pull request merged**
